### PR TITLE
Cycle 4

### PR DESCRIPTION
**Pull request by rebekah9969**
New cycle 4 templates have been added to the proposal template page.

### CODE REVIEW

**Review by mrtommyb — COMMENTED** [review]
The latex files have the wrong extension. Please change to tex

**Comment by mrtommyb** [comment]
I have time now. I can make the fix. I will am also going to change the file structure

**Comment by rebekah9969** [comment]
Ah sorry - just saw this. Thank you

**Review by mrtommyb — APPROVED** [review]
All looks good to me

**Pull request merged**
