### PR TITLE
Merge rebekah's new banner into main

### PR DESCRIPTION
**Pull request by mrtommyb**

### CODE REVIEW

**Comment by mrtommyb** [comment]
I think we need to do a little more work on the banner before we merge this

**Comment by mrtommyb** [comment]
Ok, one last thing. When I make the window really wide, the text on the banner is not all visible

**Comment by mrtommyb** [comment]
Screenshot from 2020-11-03 16-15-30

**Comment by mrtommyb** [comment]
Maybe this shouldn't be a blocker on the merge. But I wonder if there is a way to make the image have a max-width?

**Comment by mrtommyb** [comment]
If we can't get this fixed today, I say we merge and make an issue to fix at a later date.

**Comment by rebekah9969** [comment]
I think I fixed the issue with the text - I worry that it may look too small at larger sizes now though. 
The size of the image seems to increase no matter the fixed width I add.

**Comment by mrtommyb** [comment]
I'm not sure this fixed it. Did you see the attached image in a previous comment

**Comment by rebekah9969** [comment]
Screen Shot 2020-11-04 at 4 02 44 PM
I am not sure I see the issue with the title page. I added in a 1vh just in case.

**Comment by mrtommyb** [comment]
Its definitely still an issue 
Screen Shot 2020-11-04 at 4 05 50 PM

**Comment by rebekah9969** [comment]
This should now be fixed - I had defined one too many vw's in the font-size style. Sorry for the delay

**Comment by rebekah9969** [comment]
Do not merge yet as new bug detected doh!

**Comment by rebekah9969** [comment]
Bugs all fixed - for now .....

**Comment by mrtommyb** [comment]
ok, I think we can merge then

**Pull request merged**
